### ISSUE TITLE
Team-3 inheriting class and variables naming from rest of the teams

### ISSUE THREAD

**Issue by shrvenkataraman** [asrayousuf/ScrabbleWordRecommender#10]

**Comment by shrvenkataraman** [comment]
So, we will first assign some random names and then edit the file naming according to their functions

**Comment by aravindsrivats** [comment]
Yes. You can refactor the code at the end.

Create an issue after you receive code changes from other teams for changing the variable names.  Assign it to one member of your group.  He/she should finish it, push it and close the issue.
