### ISSUE TITLE
Two Word Classes

### ISSUE THREAD

**Issue by ekanshmittal** [asrayousuf/ScrabbleWordRecommender#15]
Two word classes. Please remove the one in ScrabbleWordSuggester.java. Team 1

**Comment by shrvenkataraman** [comment]
Team 3 has updated the Word.java class. Just remove the ScrabbleWordSuggester's version of Word and use Word.java instead.

**Comment by aravindsrivats** [comment]
Yes.

**Comment by aravindsrivats** [comment]
Issue Fixed. Closed.
