### ISSUE TITLE
Create anagram map from the dictionary

### ISSUE THREAD

**Issue by aravindsrivats** [asrayousuf/ScrabbleWordRecommender#17]
Creating the anagram map from the dictionary file to store all words in the format:
 key = anagram string ; value = all possible strings with that anagram

**Comment by aravindsrivats** [comment]
We are using a anagram map to store the words @asrayousuf  @aravindram94  so that we don't have to compare the same words twice.

**Comment by nsparatkar** [comment]
@aravindsrivats : The key should be the sorted lettered word!

**Comment by aravindsrivats** [comment]
Yes. That will be the key.  The value will be a list of words and the score.

**Comment by nsparatkar** [comment]
@aravindsrivats : At which position is the score going to be?

**Comment by aravindsrivats** [comment]
I'll return you the Word object in which, the word will be each word separated by spaces and score as its common score.

**Comment by nsparatkar** [comment]
@aravindsrivats : Why a space separated list? You can have a list. It becomes easier to compute.

**Comment by aravindsrivats** [comment]
Compute what?  The score is going to be calculated using the key.

**Comment by nsparatkar** [comment]
@aravindsrivats : is there an element names score in the object? Or is it going to be appended to the list in the map?

**Comment by aravindsrivats** [comment]
This is the final structure. Map < String, String>  
Key will be sorted word.
Value will be "score anagram1 anagram2 anagram3 . . "
If there is no anagram
Value will be "score"

**Comment by aravindram94** [comment]
It cant be . bcoz after sorting u lose the word . so u cant store the score alone

**Comment by aravindsrivats** [comment]
Sorry.  It will be "score word"

**Comment by aravindram94** [comment]
But the whole point is why do u bother about the traversing the list  ! it is a performance issue man! So performance doesnot matter...

**Comment by aravindsrivats** [comment]
Its not about performance. Its about stupidity. Why go over the same set of characters again and again?

**Comment by aravindram94** [comment]
okay!

**Comment by aravindram94** [comment]
can v discuss about the signature of the function?

**Comment by aravindsrivats** [comment]
Map of the following structure is generated.
Map <String, String>
