### ISSUE TITLE
Find all possible strings from the input rack

### ISSUE THREAD

**Issue by aravindsrivats** [asrayousuf/ScrabbleWordRecommender#18]
Compare and find all possible words from the anagram map for the particular input rack

**Comment by aravindsrivats** [comment]
Algorithm to find the words

for each word in dictionary:
        take first letter of rack
        if letter found in word
              remove letter from word and rack
if word is empty
       possible_word.add(current word)

**Comment by aravindsrivats** [comment]
For blank spaces the algorithm is gonna work like this:

for each word in dictionary:
        take first letter of rack
        if letter found in word
              remove letter from word and rack
if remaining length of word is equal to the number of blank spaces
       possible_word.add(current word)

**Comment by asrayousuf** [comment]
and where does anagram come into the scene.. now you search only the key of the anagram lis? and then add all the words that are there in the value?

**Comment by aravindsrivats** [comment]
Exactly. You dont need to check for each of the values!

**Comment by aravindsrivats** [comment]
We'll get the input from the second team module as (rack, number of blank spaces)

**Comment by asrayousuf** [comment]
Or we can have two overloaded functions

**Comment by aravindram94** [comment]
Aravind ! if the second passes that to us wat wil they do?

**Comment by aravindsrivats** [comment]
We'll return the score of the word including the blank tile. They'll return the proper score after subtracting the scores of blank tiles.

**Comment by aravindram94** [comment]
okay!

**Comment by aravindram94** [comment]
what sld i do now?

**Comment by aravindram94** [comment]
can v discuss the function signature?

**Comment by aravindram94** [comment]
The function receives the rack and number of blanks as input and returns the list of possible words in an ArrayList as output is done
