### ISSUE TITLE
Group 1 Work Allocation

### ISSUE THREAD

**Issue by asrayousuf** [asrayousuf/ScrabbleWordRecommender#2]
How do we distribute the work amongst the three of us? I have a basic running code which gives the desired output or do you want to start from scratch
@aravindsrivats @aravindram94

**Comment by aravindram94** [comment]
Does ur code uses the same logic as u stated in the other issue tracker?

**Comment by Jayasruthi** [comment]
Use the same code

**Comment by theCuriosityEnthusiast** [comment]
Is the input format of the String " ansv\* "?

**Comment by theCuriosityEnthusiast** [comment]
Will the String provided be already sorted?

**Comment by asrayousuf** [comment]
Which string are you talking about?

**Comment by aravindram94** [comment]
please Split the work among ourselves group 1

**Comment by asrayousuf** [comment]
Okay so our work allocation will go like this:

Aravind AR: Generate the Anagram list. Returns a Hash Map with key=<sorted word>, value=<list of anagrams separated by String>
Aravind S: Code the function for calculating the score of each word
Asra: Incorporate the code and generate the top 10/5 best suggested words

**Comment by asrayousuf** [comment]
Is this okay?

**Comment by asrayousuf** [comment]
Open to changes?

**Comment by Jayasruthi** [comment]
Check this code:
https://github.com/DhanyaHN/ScrabbleWordSuggester

**Comment by aravindsrivats** [comment]
Who is taking care of calling the respective function based on the input?

**Comment by Jayasruthi** [comment]
Hey is the constraint input "**_c_p" or "   c p"
