### ISSUE TITLE
Workflow issue - Blank Handling

### ISSUE THREAD

**Issue by harr93** [asrayousuf/ScrabbleWordRecommender#21]
Team 1's function calls BlankHandling in case of a blank in the rack. What does the blank function return?

**Comment by aravindsrivats** [comment]
Your module should have hasBlankTIles, countBlankTiles, getRackWithoutBlankTiles

**Comment by harr93** [comment]
Okay. Closing the issue.

**Comment by aravindsrivats** [comment]
and calculateScoreWithBlankTiles

**Comment by aravindsrivats** [comment]
Discuss what each of this function is going to get as input and return

**Comment by harr93** [comment]
The hasBlankTiles function gets a String(rack) as input and will return true or false based on whether the rack contains Blank Tiles or not.

The countBlankTiles function gets a String(rack) as input and returns an integer which gives the number of occurrences of the Blank Tile.

The getRackWithoutBlankTiles function gets s String(rack) as input and returns the String with Blank Tiles removed as output.
