### ISSUE TITLE
Writing method for creating the regex pattern from constraint

### ISSUE THREAD

**Issue by ekanshmittal** [asrayousuf/ScrabbleWordRecommender#23]
To create the regex pattern for input constraint

**Comment by Jayasruthi** [comment]
The regex method now has 2 issues:
1. **_c_a*b -> Will work for length more than 8 
2. **_c_a_b -> Will not work for *__c_ or c_a_

**Comment by aravindsrivats** [comment]
I dont understand what the issue is. Explain more.

**Comment by ekanshmittal** [comment]
implemented
