### ISSUE TITLE
Group 2 Work Allocation

### ISSUE THREAD

**Issue by aravindsrivats** [asrayousuf/ScrabbleWordRecommender#3]
Harish, Neel and Mohanish discuss and conclude to which task each of you are going to work on.

**Comment by theCuriosityEnthusiast** [comment]
Input Format = String of this type "abcde*"

**Comment by theCuriosityEnthusiast** [comment]
Will the string be already sorted?

**Comment by harr93** [comment]
Assume it won't be sorted.

**Comment by harr93** [comment]
WE can sort it ourserlves

**Comment by nsparatkar** [comment]
Dont chat here. Its an issue tracker.
And Mohanish, what do you mean by input? Is it the rack?

**Comment by theCuriosityEnthusiast** [comment]
void function(input);
this is input..

**Comment by aravindsrivats** [comment]
What task each of you are working on?

**Comment by aravindsrivats** [comment]
How are you handling blank input? Are you going to substitute one character every time and check or assign random character?

**Comment by theCuriosityEnthusiast** [comment]
Okay I'll tell you..
Lets say the word is "cnt".. then we have _c_n_t_ ( '_' indicates where the
letters can be put) so that we can have 'cant' or 'bcnt' etc..

**Comment by theCuriosityEnthusiast** [comment]
Then we realize that only [a-c] can go before c; only [d-n] can go before n
and after c; and only [o-t] can go before t and after n; and [u-z] goes
after t..

**Comment by theCuriosityEnthusiast** [comment]
So run a for-loop from a to z and put the characters in proper places. If
more than one spaces are there do this recursively on the newly formed
word..

**Comment by theCuriosityEnthusiast** [comment]
We are not generating all the words, instead we are generating keys for the
hashmap. From there you can retrieve the actual words.

**Comment by aravindsrivats** [comment]
I need to know who is doing which part of the task

**Comment by harr93** [comment]
We were planning to split the work in the following fashion: Mohanish will write the fill_blanks function which, given a string and the number of blank spaces will fill the blanks, Neel will write the score calculating function and I will write the interface function that would call the other functions and return the results.
The main problem here is that with the new data structure, all the ideas we had have gone out the window.

**Comment by aravindsrivats** [comment]
The scoring function happens in the pre-computation part. You have to compute the score to be subtracted from the score due to the blank tiles.

**Comment by aravindsrivats** [comment]
Raise a new issue for scoring and lets discuss on it.

**Comment by harr93** [comment]
Let's close these work allocation issues.
