### ISSUE TITLE
Team 3 Integration

### ISSUE THREAD

**Issue by ekanshmittal** [asrayousuf/ScrabbleWordRecommender#31]
What all functions from pattern matching you need( there input parameters and output). Please Specify.
We have two functions now 
public String appendConstraintLetters(String constraintPattern, String tiles) ;
public List String applyPatternMatching(List  String possibleWords, String constraintPattern) ;

Please integrate them asap in the code. we need to do testing.

**Comment by aravindsrivats** [comment]
We'll call the constructor with Class(String tiles, String constraint)
For the input string we'll need , inputStringWithConstraints() which will return the constraint characters appended to input.

**Comment by ekanshmittal** [comment]
no use the public String appendConstraintLetters(String constraintPattern, String tiles) ;  to append constraint characters. then call public List String applyPatternMatching(List String possibleWords, String constraintPattern) ; for pattern matching

**Comment by aravindsrivats** [comment]
Okay. I understand.
