### ISSUE TITLE
Constraint handling function

### ISSUE THREAD

**Issue by aravindsrivats** [asrayousuf/ScrabbleWordRecommender#32]
Our findPossibleWords will return a HashMap<String, String>
String 1 is the Key = sorted word
String 2 is value = "score word1 word2 word3 . . ."

But you have implemented a List<String>. How are we change that?

**Comment by ekanshmittal** [comment]
```
ArrayList<String> findPossibleWords(String rack, int numOfBlanks) {
```

it is returning arraylist

**Comment by ekanshmittal** [comment]
modify and pass us arrayList

**Comment by aravindsrivats** [comment]
We'll have to re-form your result back into the HashMap. That is a problem.

**Comment by ekanshmittal** [comment]
but u are passing arraylist in the first list
check the code

**Comment by ekanshmittal** [comment]
Have changed the return type to HashMap<String, String>.
