### ISSUE TITLE
Regular Expression for * and ?

### ISSUE THREAD

**Issue by aravindsrivats** [asrayousuf/ScrabbleWordRecommender#38]
Need a regular expression match that differentiates between any number of characters and particular number of characters.

**Comment by Jayasruthi** [comment]
Can you give me an example? Why do you need this feature?

**Comment by aravindsrivats** [comment]
If i give *_A_B, it should match for zero or more character before A and between B
If I give ..A.B it should match only for 2 characters before A and one character between B

**Comment by Jayasruthi** [comment]
I haven't handled any characters before or after. It will just be dot between all characters. So \* \* \* C \* \* A \* will match CLLA, LLCLLA, LLLCLLALLL

**Comment by aravindsrivats** [comment]
Exactly. That is when I pass a \* 
How are you going to handle the case I have explained above? If I pass a '.' it should exactly match one character.

**Comment by Jayasruthi** [comment]
If you pass A \* it will change it to A dot.  But if you pass A \* \* it will not change it to A dot dot
