### ISSUE TITLE
Group 3 Work Allocation

### ISSUE THREAD

**Issue by aravindsrivats** [asrayousuf/ScrabbleWordRecommender#4]
Jayasruthi, Shravan and Ekansh discuss about which task each of you are gonna perform so that I can create issues for each of you.

**Comment by Jayasruthi** [comment]
Ekansh generate new rack
Shravan pattern matching.

**Comment by aravindsrivats** [comment]
Everyone should push their code. Not just Jayasruthi

**Comment by aravindsrivats** [comment]
I'll set up issue tracker for each of your work

**Comment by Jayasruthi** [comment]
Team 3:
Ekansh: Get letters from constraint and append to rack.
Jayasruthi: Convert the constraint to a regex
Shravan: Pattern match with regex
